name: flutter_core_kit
description: "Flutter Core Kit"
version: 1.0.4
homepage: https://github.com/christhapa98/flutter_core_kit/

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # network
  dio: ^5.8.0+1
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4

  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
